### ISSUE TITLE
Add support for change selinux type of folder

### ISSUE THREAD

**Issue by agustik** [pall-valmundsson/puppet-createrepo#16]
I'm exporting repo with nginx, SElinux label for repo folders need to be httpd_sys_content_t and recurse set to true.
If not set to httpd_sys_content_t then puppet will set it to var_t 

validate_bool($manage_repo_dirs)
    if $manage_repo_dirs {
        file { [$repository_dir, $repo_cache_dir]:
            ensure => directory,
            seltype=> 'httpd_sys_content_t',  
            recurse=> true,
            owner  => $repo_owner,
            group  => $repo_group,
            mode   => '0775',
        }
    }

**Comment by pall-valmundsson** [comment]
Will look into this asap.
