### ISSUE TITLE
chmod scuffle between puppet and createrepo calls

### ISSUE THREAD

**Issue by michalkoza** [pall-valmundsson/puppet-createrepo#29]
Hello Pall!
I just noticed that using repo_group and repo_recurse can lead to situation when shell `createrepo` calls as root and `puppet` runs change `repodata` folder group back and forth from root to whatever is used as repo_group. 
I considered making pull request with a fix but can't decide between two solutions:
1) exposing `file`'s resource `ignore` property and let users take care about details
2) excluding `repodata` folder and its content inside the module without extending its interface

What do you think?

**Comment by pall-valmundsson** [comment]
Hi. Is there a good reason for using root to call createrepo instead of the repo owner?

**Comment by michalkoza** [comment]
Well in my case `root` is the repo owner. But the issue is not with the owner, but with the group.
The scenario is that all members of `dev` group are allowed to put rpms to the repo. Thus I recursively set `owner=root`,  `group=dev` on entire repo using the `repo_goroup` and `repo_recurse` properties. 
But rebuilding the repo is only allowed through `sudo`. This results in setting `owner=root`, `group=root` on all contents of `repodata` folder. I'm ok with that state but now puppet on each run will try to make it `owner=root`,  `group=dev` again.

In fact it would be similar if `bob` was the repo owner instead of `root`. Calls to `createrepo` would set `group` to `bob`'s effective group which could be still different than `dev`.

**Comment by pall-valmundsson** [comment]
Ah, I see. I'd rather have the ignore parameter exposed in a backward compatible manner, and document this use-case in some way, than being opinionated and forcibly excluding the repodata directory.

**Comment by pall-valmundsson** [comment]
Addressed in #30 and #31
